#!/usr/bin/env python3
"""
Waterway Route Calculator

This script calculates waterway routes between input points using the graph data
generated by osm_waterway_extractor.py. It reads nodes.json.gz and edges.json.gz
files and computes optimal routes through the waterway network.

Usage:
    python waterway_route_calculator.py nodes.json.gz edges.json.gz lat1,lon1 lat2,lon2 [lat3,lon3 ...]

Features:
- Uses only libraries that can be easily migrated to Flutter/Dart
- Handles disconnected networks with straight-line connections
- Provides comprehensive debug information
- Outputs GeoJSON format with route geometry
"""

import json
import gzip
import sys
import math
import heapq
import argparse
from typing import List, Tuple, Dict, Optional, Set
from dataclasses import dataclass


@dataclass
class Point:
    """Represents a geographic point with latitude and longitude."""
    lat: float
    lon: float
    
    def distance_to(self, other: 'Point') -> float:
        """Calculate geodesic distance to another point using Haversine formula."""
        return haversine_distance(self.lat, self.lon, other.lat, other.lon)


@dataclass
class Edge:
    """Represents a waterway edge in the graph."""
    id: int
    start_node: int
    end_node: int
    length: float
    coordinates: List[Tuple[float, float]]  # List of (lat, lon) pairs
    
    def get_closest_point_on_edge(self, point: Point) -> Tuple[Point, float]:
        """Find the closest point on this edge to the given point."""
        min_distance = float('inf')
        closest_point = Point(0.0, 0.0)
        
        # Check each segment of the edge
        for i in range(len(self.coordinates) - 1):
            start_lat, start_lon = self.coordinates[i]
            end_lat, end_lon = self.coordinates[i + 1]
            
            # Find closest point on this segment
            segment_closest = closest_point_on_segment(
                point.lat, point.lon,
                start_lat, start_lon,
                end_lat, end_lon
            )
            
            distance = point.distance_to(Point(segment_closest[0], segment_closest[1]))
            if distance < min_distance:
                min_distance = distance
                closest_point = Point(segment_closest[0], segment_closest[1])
        
        return closest_point, min_distance


def haversine_distance(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Calculate the geodesic distance between two points using Haversine formula."""
    R = 6371000  # Earth's radius in meters
    
    # Convert to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)
    
    # Haversine formula
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    
    a = (math.sin(dlat / 2) ** 2 + 
         math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    return R * c


def closest_point_on_segment(px: float, py: float, 
                           ax: float, ay: float, 
                           bx: float, by: float) -> Tuple[float, float]:
    """Find the closest point on line segment AB to point P."""
    # Vector from A to B
    ab_x = bx - ax
    ab_y = by - ay
    
    # Vector from A to P
    ap_x = px - ax
    ap_y = py - ay
    
    # Project AP onto AB
    ab_length_sq = ab_x * ab_x + ab_y * ab_y
    
    if ab_length_sq == 0:
        # A and B are the same point
        return (ax, ay)
    
    t = (ap_x * ab_x + ap_y * ab_y) / ab_length_sq
    
    # Clamp t to [0, 1] to stay on the segment
    t = max(0, min(1, t))
    
    # Calculate the closest point
    closest_x = ax + t * ab_x
    closest_y = ay + t * ab_y
    
    return (closest_x, closest_y)


class WaterwayGraph:
    """Represents the waterway network graph."""
    
    def __init__(self, nodes: List[Tuple[float, float]], edges: List[Dict]):
        self.nodes = [Point(lat, lon) for lat, lon in nodes]
        self.edges = []
        self.adjacency_list = {}
        
        # Build edge objects and adjacency list
        for i, edge_data in enumerate(edges):
            edge = Edge(
                id=i,
                start_node=edge_data['start'],
                end_node=edge_data['end'],
                length=edge_data['length'],
                coordinates=edge_data['coordinates']
            )
            self.edges.append(edge)
            
            # Build adjacency list for pathfinding
            start = edge_data['start']
            end = edge_data['end']
            
            if start not in self.adjacency_list:
                self.adjacency_list[start] = []
            if end not in self.adjacency_list:
                self.adjacency_list[end] = []
                
            self.adjacency_list[start].append((end, edge.length, i))
            self.adjacency_list[end].append((start, edge.length, i))
    
    def find_closest_edge(self, point: Point) -> Tuple[Edge, Point, float]:
        """Find the closest edge to the given point."""
        if not self.edges:
            raise ValueError("No edges available in the graph")
        
        min_distance = float('inf')
        closest_edge = self.edges[0]  # Initialize with first edge
        closest_point_on_edge = Point(0.0, 0.0)  # Will be overwritten
        
        print(f"  Searching through {len(self.edges)} edges for closest to ({point.lat:.6f}, {point.lon:.6f})")
        
        for edge in self.edges:
            edge_closest_point, distance = edge.get_closest_point_on_edge(point)
            
            if distance < min_distance:
                min_distance = distance
                closest_edge = edge
                closest_point_on_edge = edge_closest_point
        
        print(f"  Found closest edge {closest_edge.id} at distance {min_distance:.2f}m")
        print(f"  Closest point on edge: ({closest_point_on_edge.lat:.6f}, {closest_point_on_edge.lon:.6f})")
        
        return closest_edge, closest_point_on_edge, min_distance
    
    def dijkstra(self, start_node: int, end_node: int) -> Tuple[List[int], float]:
        """Find shortest path between two nodes using Dijkstra's algorithm."""
        if start_node == end_node:
            return [start_node], 0.0
        
        distances = {node: float('inf') for node in range(len(self.nodes))}
        distances[start_node] = 0.0
        previous = {}
        visited = set()
        
        # Priority queue: (distance, node_id)
        pq = [(0.0, start_node)]
        
        while pq:
            current_distance, current_node = heapq.heappop(pq)
            
            if current_node in visited:
                continue
                
            visited.add(current_node)
            
            if current_node == end_node:
                # Reconstruct path
                path = []
                node = end_node
                while node is not None:
                    path.append(node)
                    node = previous.get(node)
                path.reverse()
                return path, distances[end_node]
            
            # Check neighbors
            if current_node in self.adjacency_list:
                for neighbor, edge_length, edge_id in self.adjacency_list[current_node]:
                    if neighbor not in visited:
                        new_distance = current_distance + edge_length
                        
                        if new_distance < distances[neighbor]:
                            distances[neighbor] = new_distance
                            previous[neighbor] = current_node
                            heapq.heappush(pq, (new_distance, neighbor))
        
        # No path found
        return [], float('inf')
    
    def dijkstra_to_all_reachable(self, start_node: int) -> Tuple[Dict[int, float], Dict[int, int]]:
        """Find shortest distances and paths from start_node to all reachable nodes."""
        distances = {node: float('inf') for node in range(len(self.nodes))}
        distances[start_node] = 0.0
        previous = {}
        visited = set()
        
        # Priority queue: (distance, node_id)
        pq = [(0.0, start_node)]
        
        while pq:
            current_distance, current_node = heapq.heappop(pq)
            
            if current_node in visited:
                continue
                
            visited.add(current_node)
            
            # Check neighbors
            if current_node in self.adjacency_list:
                for neighbor, edge_length, edge_id in self.adjacency_list[current_node]:
                    if neighbor not in visited:
                        new_distance = current_distance + edge_length
                        
                        if new_distance < distances[neighbor]:
                            distances[neighbor] = new_distance
                            previous[neighbor] = current_node
                            heapq.heappush(pq, (new_distance, neighbor))
        
        return distances, previous
    
    def find_farthest_reachable_towards_target(self, start_node: int, target_point: Point) -> Tuple[int, float, float]:
        """Find the farthest reachable node from start_node in the direction of target_point."""
        distances, previous = self.dijkstra_to_all_reachable(start_node)
        
        best_node = start_node
        best_distance_along_waterway = 0.0
        best_distance_to_target = self.nodes[start_node].distance_to(target_point)
        
        # Find the reachable node that gets closest to the target (minimizes straight-line distance to target)
        # while using the waterway network as much as possible
        for node_id, waterway_distance in distances.items():
            if waterway_distance != float('inf') and waterway_distance > 0:  # Node is reachable and not the start
                node_point = self.nodes[node_id]
                distance_to_target = node_point.distance_to(target_point)
                
                # Prefer nodes that get closer to the target, prioritizing longer waterway distances for ties
                if (distance_to_target < best_distance_to_target or 
                    (distance_to_target == best_distance_to_target and waterway_distance > best_distance_along_waterway)):
                    best_node = node_id
                    best_distance_along_waterway = waterway_distance
                    best_distance_to_target = distance_to_target
        
        return best_node, best_distance_along_waterway, best_distance_to_target
    
    def reconstruct_path_to_node(self, target_node: int, previous: Dict[int, int], start_node: int) -> List[int]:
        """Reconstruct path from start_node to target_node using previous dictionary."""
        if target_node not in previous and target_node != start_node:
            return []
        
        path = []
        node = target_node
        while node is not None:
            path.append(node)
            node = previous.get(node)
        path.reverse()
        return path
    
    def get_path_geometry(self, node_path: List[int]) -> List[Tuple[float, float]]:
        """Get the geometry coordinates for a path through nodes."""
        if len(node_path) < 2:
            return []
        
        geometry = []
        
        for i in range(len(node_path) - 1):
            start_node = node_path[i]
            end_node = node_path[i + 1]
            
            # Find the edge connecting these nodes
            edge_found = False
            for edge in self.edges:
                if ((edge.start_node == start_node and edge.end_node == end_node) or
                    (edge.start_node == end_node and edge.end_node == start_node)):
                    
                    # Add edge coordinates (in correct direction)
                    edge_coords = edge.coordinates.copy()
                    if edge.start_node == end_node:  # Reverse direction
                        edge_coords.reverse()
                    
                    # Add coordinates, avoiding duplicates at junctions
                    if not geometry:
                        geometry.extend(edge_coords)
                    else:
                        geometry.extend(edge_coords[1:])  # Skip first coordinate to avoid duplicate
                    
                    edge_found = True
                    break
            
            if not edge_found:
                print(f"  Warning: No edge found between nodes {start_node} and {end_node}")
                # Add straight line as fallback
                if not geometry:
                    geometry.append((self.nodes[start_node].lat, self.nodes[start_node].lon))
                geometry.append((self.nodes[end_node].lat, self.nodes[end_node].lon))
        
        return geometry


class WaterwayRouteCalculator:
    """Main route calculator class."""
    
    def __init__(self, nodes_file: str, edges_file: str):
        print(f"Loading waterway network from {nodes_file} and {edges_file}")
        
        # Load nodes
        with gzip.open(nodes_file, 'rt', encoding='utf-8') as f:
            nodes_data = json.load(f)
        print(f"Loaded {len(nodes_data)} nodes")
        
        # Load edges
        with gzip.open(edges_file, 'rt', encoding='utf-8') as f:
            edges_data = json.load(f)
        print(f"Loaded {len(edges_data)} edges")
        
        # Build graph
        self.graph = WaterwayGraph(nodes_data, edges_data)
        print(f"Built graph with {len(self.graph.nodes)} nodes and {len(self.graph.edges)} edges")
    
    def calculate_route(self, waypoints: List[Point]) -> Dict:
        """Calculate route through multiple waypoints."""
        print(f"\n{'='*60}")
        print(f"WATERWAY ROUTE CALCULATION")
        print(f"{'='*60}")
        print(f"Waypoints: {len(waypoints)}")
        for i, wp in enumerate(waypoints):
            print(f"  {i+1}: ({wp.lat:.6f}, {wp.lon:.6f})")
        
        route_segments = []
        total_distance = 0.0
        all_geometry = []
        
        for i in range(len(waypoints) - 1):
            start_point = waypoints[i]
            end_point = waypoints[i + 1]
            
            print(f"\n--- Segment {i+1}: Waypoint {i+1} to Waypoint {i+2} ---")
            
            # Find closest edges to start and end points
            print(f"Finding closest edge to start point ({start_point.lat:.6f}, {start_point.lon:.6f})")
            start_edge, start_point_on_edge, start_distance = self.graph.find_closest_edge(start_point)
            
            print(f"Finding closest edge to end point ({end_point.lat:.6f}, {end_point.lon:.6f})")
            end_edge, end_point_on_edge, end_distance = self.graph.find_closest_edge(end_point)
            
            # Check if we need to connect to the waterway network
            segment_geometry = []
            segment_distance = 0.0
            
            # Add straight line from waypoint to closest point on start edge
            if start_distance > 0.1:  # Only add if not already on the edge
                print(f"Adding straight line from waypoint to waterway network ({start_distance:.2f}m)")
                segment_geometry.append((start_point.lat, start_point.lon))
                segment_distance += start_distance
            
            segment_geometry.append((start_point_on_edge.lat, start_point_on_edge.lon))
            
            # Find path through waterway network
            if start_edge.id == end_edge.id:
                print(f"Start and end points are on the same edge {start_edge.id}")
                # Points are on the same edge - add direct connection
                segment_geometry.append((end_point_on_edge.lat, end_point_on_edge.lon))
                segment_distance += start_point_on_edge.distance_to(end_point_on_edge)
            else:
                print(f"Finding waterway path from edge {start_edge.id} to edge {end_edge.id}")
                
                # Enhanced routing for disconnected networks
                route_segments_found = self._find_disconnected_route(
                    start_edge, start_point_on_edge, 
                    end_edge, end_point_on_edge, 
                    end_point
                )
                
                # Add all route segments to geometry
                for route_segment in route_segments_found:
                    segment_geometry.extend(route_segment['geometry'])
                    segment_distance += route_segment['distance']
                    print(f"  Added route segment: {route_segment['type']}, {route_segment['distance']:.2f}m, {len(route_segment['geometry'])} points")
            
            # Add straight line from closest point on end edge to waypoint
            if end_distance > 0.1:  # Only add if not already on the edge
                print(f"Adding straight line from waterway network to waypoint ({end_distance:.2f}m)")
                segment_geometry.append((end_point.lat, end_point.lon))
                segment_distance += end_distance
            
            print(f"Segment {i+1} completed: {segment_distance:.2f}m, {len(segment_geometry)} coordinates")
            
            route_segments.append({
                'start_waypoint': i + 1,
                'end_waypoint': i + 2,
                'distance_m': segment_distance,
                'geometry': segment_geometry,
                'start_edge_id': start_edge.id,
                'end_edge_id': end_edge.id,
                'start_edge_distance_m': start_distance,
                'end_edge_distance_m': end_distance
            })
            
            total_distance += segment_distance
            all_geometry.extend(segment_geometry)
        
        print(f"\n{'='*60}")
        print(f"ROUTE CALCULATION SUMMARY")
        print(f"{'='*60}")
        print(f"Total distance: {total_distance:.2f}m")
        print(f"Total geometry points: {len(all_geometry)}")
        print(f"Route segments: {len(route_segments)}")
        
        return {
            'type': 'route_calculation_result',
            'total_distance_m': total_distance,
            'total_geometry_points': len(all_geometry),
            'segments': route_segments,
            'geometry': all_geometry
        }
    
    def _find_disconnected_route(self, start_edge: Edge, start_point_on_edge: Point, 
                                end_edge: Edge, end_point_on_edge: Point, 
                                end_waypoint: Point) -> List[Dict]:
        """Find route through potentially disconnected waterway network."""
        route_segments = []
        
        # First, try direct connection between edges
        best_direct_path = []
        best_direct_distance = float('inf')
        
        # Try all combinations of start/end nodes from the two edges
        start_nodes = [start_edge.start_node, start_edge.end_node]
        end_nodes = [end_edge.start_node, end_edge.end_node]
        
        for start_node in start_nodes:
            for end_node in end_nodes:
                path, distance = self.graph.dijkstra(start_node, end_node)
                if path and distance < best_direct_distance:
                    best_direct_path = path
                    best_direct_distance = distance
                    print(f"  Found direct path via nodes {start_node} -> {end_node}: {len(path)} nodes, {distance:.2f}m")
        
        if best_direct_path:
            print(f"Using direct waterway path: {len(best_direct_path)} nodes, {best_direct_distance:.2f}m")
            path_geometry = self.graph.get_path_geometry(best_direct_path)
            
            if path_geometry:
                route_segments.append({
                    'type': 'waterway_path',
                    'geometry': path_geometry,
                    'distance': best_direct_distance,
                    'nodes': best_direct_path
                })
            
            route_segments.append({
                'type': 'connection_to_end',
                'geometry': [(end_point_on_edge.lat, end_point_on_edge.lon)],
                'distance': 0.0,
                'nodes': []
            })
            
            return route_segments
        
        # No direct path found - route through waterway network as far as possible
        print(f"No direct path found - analyzing disconnected network routing")
        
        # Find the best path from start towards destination through waterway network
        best_start_route = None
        best_start_endpoint = None
        best_start_distance = 0.0
        
        for start_node in start_nodes:
            # Get all reachable nodes from this start node
            distances, previous = self.graph.dijkstra_to_all_reachable(start_node)
            
            # Find the node that gets closest to the destination
            best_endpoint_for_this_start = start_node
            best_distance_to_destination = self.nodes[start_node].distance_to(end_waypoint)
            best_waterway_distance = 0.0
            
            for node_id, waterway_distance in distances.items():
                if waterway_distance != float('inf'):
                    node_point = self.nodes[node_id]
                    distance_to_destination = node_point.distance_to(end_waypoint)
                    
                    # Choose the node that gets closest to the destination
                    if (distance_to_destination < best_distance_to_destination or
                        (distance_to_destination == best_distance_to_destination and waterway_distance > best_waterway_distance)):
                        best_endpoint_for_this_start = node_id
                        best_distance_to_destination = distance_to_destination
                        best_waterway_distance = waterway_distance
            
            print(f"  From start node {start_node}: best endpoint {best_endpoint_for_this_start}, waterway distance {best_waterway_distance:.2f}m, remaining distance {best_distance_to_destination:.2f}m")
            
            # Choose the start node that produces the best overall result
            if (best_start_route is None or 
                best_distance_to_destination < best_start_endpoint[1] or
                (best_distance_to_destination == best_start_endpoint[1] and best_waterway_distance > best_start_distance)):
                
                best_start_route = self.graph.reconstruct_path_to_node(best_endpoint_for_this_start, previous, start_node)
                best_start_endpoint = (best_endpoint_for_this_start, best_distance_to_destination)
                best_start_distance = best_waterway_distance
        
        if best_start_route and best_start_distance > 0:
            print(f"Best start route: {len(best_start_route)} nodes, {best_start_distance:.2f}m")
            
            # Add waterway segment from start
            start_path_geometry = self.graph.get_path_geometry(best_start_route)
            if start_path_geometry:
                route_segments.append({
                    'type': 'waterway_path_start_component',
                    'geometry': start_path_geometry,
                    'distance': best_start_distance,
                    'nodes': best_start_route
                })
                print(f"  Added start component waterway path: {len(best_start_route)} nodes, {best_start_distance:.2f}m")
            
            # Try to find a route in the destination network
            start_endpoint_point = self.graph.nodes[best_start_endpoint[0]]
            
            best_end_route = None
            best_end_startpoint = None
            best_end_distance = 0.0
            best_bridge_distance = float('inf')
            
            for end_node in end_nodes:
                # Get all reachable nodes from this end node
                distances, previous = self.graph.dijkstra_to_all_reachable(end_node)
                
                # Find the node that gets closest to our start endpoint
                best_bridge_point = end_node
                best_bridge_dist = start_endpoint_point.distance_to(self.graph.nodes[end_node])
                best_waterway_dist = 0.0
                
                for node_id, waterway_distance in distances.items():
                    if waterway_distance != float('inf'):
                        node_point = self.graph.nodes[node_id]
                        bridge_distance = start_endpoint_point.distance_to(node_point)
                        
                        # Choose the node that minimizes bridge distance
                        if (bridge_distance < best_bridge_dist or
                            (bridge_distance == best_bridge_dist and waterway_distance > best_waterway_dist)):
                            best_bridge_point = node_id
                            best_bridge_dist = bridge_distance
                            best_waterway_dist = waterway_distance
                
                print(f"  From end node {end_node}: best bridge point {best_bridge_point}, bridge distance {best_bridge_dist:.2f}m, waterway distance {best_waterway_dist:.2f}m")
                
                # Choose the end route that minimizes bridge distance
                if best_bridge_dist < best_bridge_distance:
                    best_end_route = self.graph.reconstruct_path_to_node(end_node, previous, best_bridge_point)
                    best_end_startpoint = best_bridge_point
                    best_end_distance = best_waterway_dist
                    best_bridge_distance = best_bridge_dist
            
            # Add bridge connection
            if best_end_startpoint is not None:
                bridge_start = self.graph.nodes[best_start_endpoint[0]]
                bridge_end = self.graph.nodes[best_end_startpoint]
                
                route_segments.append({
                    'type': 'straight_line_bridge',
                    'geometry': [(bridge_start.lat, bridge_start.lon), (bridge_end.lat, bridge_end.lon)],
                    'distance': best_bridge_distance,
                    'nodes': [best_start_endpoint[0], best_end_startpoint]
                })
                print(f"  Added straight line bridge: {best_bridge_distance:.2f}m")
                
                # Add end waterway segment if it exists
                if best_end_route and best_end_distance > 0:
                    end_path_geometry = self.graph.get_path_geometry(best_end_route)
                    if end_path_geometry:
                        route_segments.append({
                            'type': 'waterway_path_end_component',
                            'geometry': end_path_geometry,
                            'distance': best_end_distance,
                            'nodes': best_end_route
                        })
                        print(f"  Added end component waterway path: {len(best_end_route)} nodes, {best_end_distance:.2f}m")
            else:
                # Direct bridge to end point
                bridge_start = self.graph.nodes[best_start_endpoint[0]]
                bridge_distance = bridge_start.distance_to(end_waypoint)
                
                route_segments.append({
                    'type': 'straight_line_bridge',
                    'geometry': [(bridge_start.lat, bridge_start.lon), (end_waypoint.lat, end_waypoint.lon)],
                    'distance': bridge_distance,
                    'nodes': [best_start_endpoint[0]]
                })
                print(f"  Added direct bridge to destination: {bridge_distance:.2f}m")
        else:
            # Fallback to straight line if no meaningful waterway routing possible
            print(f"No meaningful waterway routing possible - using straight line")
            bridge_distance = start_point_on_edge.distance_to(end_point_on_edge)
            route_segments.append({
                'type': 'straight_line_fallback',
                'geometry': [(start_point_on_edge.lat, start_point_on_edge.lon), (end_point_on_edge.lat, end_point_on_edge.lon)],
                'distance': bridge_distance,
                'nodes': []
            })
        
        # Add final connection to end edge point
        route_segments.append({
            'type': 'connection_to_end',
            'geometry': [(end_point_on_edge.lat, end_point_on_edge.lon)],
            'distance': 0.0,
            'nodes': []
        })
        
        return route_segments
    
    def create_geojson_output(self, route_result: Dict, waypoints: List[Point]) -> Dict:
        """Create GeoJSON output for the calculated route."""
        features = []
        
        # Add the main route line
        if route_result['geometry']:
            # Convert from (lat, lon) to (lon, lat) for GeoJSON
            coordinates = [[lon, lat] for lat, lon in route_result['geometry']]
            
            route_feature = {
                'type': 'Feature',
                'geometry': {
                    'type': 'LineString',
                    'coordinates': coordinates
                },
                'properties': {
                    'type': 'route',
                    'total_distance_m': route_result['total_distance_m'],
                    'segments': len(route_result['segments'])
                }
            }
            features.append(route_feature)
        
        # Add waypoint markers
        for i, waypoint in enumerate(waypoints):
            waypoint_feature = {
                'type': 'Feature',
                'geometry': {
                    'type': 'Point',
                    'coordinates': [waypoint.lon, waypoint.lat]
                },
                'properties': {
                    'type': 'waypoint',
                    'waypoint_number': i + 1
                }
            }
            features.append(waypoint_feature)
        
        # Add segment information as separate features
        for i, segment in enumerate(route_result['segments']):
            if segment['geometry']:
                segment_coordinates = [[lon, lat] for lat, lon in segment['geometry']]
                
                segment_feature = {
                    'type': 'Feature',
                    'geometry': {
                        'type': 'LineString',
                        'coordinates': segment_coordinates
                    },
                    'properties': {
                        'type': 'route_segment',
                        'segment_number': i + 1,
                        'distance_m': segment['distance_m'],
                        'start_waypoint': segment['start_waypoint'],
                        'end_waypoint': segment['end_waypoint'],
                        'start_edge_id': segment['start_edge_id'],
                        'end_edge_id': segment['end_edge_id'],
                        'start_edge_distance_m': segment['start_edge_distance_m'],
                        'end_edge_distance_m': segment['end_edge_distance_m']
                    }
                }
                features.append(segment_feature)
        
        return {
            'type': 'FeatureCollection',
            'features': features,
            'properties': {
                'generator': 'waterway_route_calculator.py',
                'calculation_summary': {
                    'total_distance_m': route_result['total_distance_m'],
                    'waypoints': len(waypoints),
                    'segments': len(route_result['segments']),
                    'geometry_points': route_result['total_geometry_points']
                }
            }
        }


def parse_coordinate_pairs(coord_strings: List[str]) -> List[Point]:
    """Parse coordinate pair strings into Point objects."""
    waypoints = []
    for coord_str in coord_strings:
        try:
            lat_str, lon_str = coord_str.split(',')
            lat = float(lat_str.strip())
            lon = float(lon_str.strip())
            waypoints.append(Point(lat, lon))
        except ValueError:
            raise ValueError(f"Invalid coordinate format: '{coord_str}'. Expected format: 'lat,lon'")
    
    return waypoints


def main():
    parser = argparse.ArgumentParser(
        description='Calculate waterway routes between waypoints using OSM waterway graph data',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python waterway_route_calculator.py test.nodes.json.gz test.edges.json.gz 52.5,13.4 52.52,13.42
  python waterway_route_calculator.py data.nodes.json.gz data.edges.json.gz -- -34.5,-56.1 -34.52,-56.12 -34.54,-56.14
  python waterway_route_calculator.py nodes.json.gz edges.json.gz 52.5,13.4 52.52,13.42 --output route.geojson

Input coordinate format: lat,lon (decimal degrees)
Output: GeoJSON with route geometry and debug information
Use -- before coordinates if they start with minus signs to avoid parsing as options.
        """
    )
    
    parser.add_argument('nodes_file', help='Path to nodes.json.gz file')
    parser.add_argument('edges_file', help='Path to edges.json.gz file')
    parser.add_argument('--output', '-o', help='Output GeoJSON file (default: print to stdout)')
    parser.add_argument('waypoints', nargs='+', help='Waypoints as lat,lon pairs')
    
    args = parser.parse_args()
    
    if len(args.waypoints) < 2:
        print("Error: At least 2 waypoints are required", file=sys.stderr)
        sys.exit(1)
    
    try:
        # Parse waypoints
        waypoints = parse_coordinate_pairs(args.waypoints)
        
        # Create route calculator
        calculator = WaterwayRouteCalculator(args.nodes_file, args.edges_file)
        
        # Calculate route
        route_result = calculator.calculate_route(waypoints)
        
        # Create GeoJSON output
        geojson_output = calculator.create_geojson_output(route_result, waypoints)
        
        # Output result
        if args.output:
            with open(args.output, 'w') as f:
                json.dump(geojson_output, f, indent=2)
            print(f"\nRoute saved to {args.output}")
        else:
            print(json.dumps(geojson_output, indent=2))
    
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()