#!/usr/bin/env python3
"""
Waterway Route Calculator

This script calculates waterway routes between input points using the graph data
generated by osm_waterway_extractor.py. It reads nodes.json.gz and edges.json.gz
files and computes optimal routes through the waterway network.

Usage:
    python waterway_route_calculator.py nodes.json.gz edges.json.gz lat1,lon1 lat2,lon2 [lat3,lon3 ...]

Features:
- Uses only libraries that can be easily migrated to Flutter/Dart
- Handles disconnected networks with straight-line connections
- Provides comprehensive debug information
- Outputs GeoJSON format with route geometry
"""

# Version identifier for tracking script updates
SCRIPT_VERSION = "2.1.3-fix-reverse-edge-geometry"

import json
import gzip
import sys
import math
import heapq
import argparse
from typing import List, Tuple, Dict, Optional, Set
from dataclasses import dataclass


@dataclass
class Point:
    """Represents a geographic point with latitude and longitude."""
    lat: float
    lon: float
    
    def distance_to(self, other: 'Point') -> float:
        """Calculate geodesic distance to another point using Haversine formula."""
        return haversine_distance(self.lat, self.lon, other.lat, other.lon)


@dataclass
class Edge:
    """Represents a waterway edge in the graph."""
    id: int
    start_node: int
    end_node: int
    length: float
    coordinates: List[Tuple[float, float]]  # List of (lat, lon) pairs
    
    def get_closest_point_on_edge(self, point: Point) -> Tuple[Point, float]:
        """Find the closest point on this edge to the given point."""
        min_distance = float('inf')
        closest_point = Point(0.0, 0.0)
        
        # Check each segment of the edge
        for i in range(len(self.coordinates) - 1):
            start_lat, start_lon = self.coordinates[i]
            end_lat, end_lon = self.coordinates[i + 1]
            
            # Find closest point on this segment
            segment_closest = closest_point_on_segment(
                point.lat, point.lon,
                start_lat, start_lon,
                end_lat, end_lon
            )
            
            distance = point.distance_to(Point(segment_closest[0], segment_closest[1]))
            if distance < min_distance:
                min_distance = distance
                closest_point = Point(segment_closest[0], segment_closest[1])
        
        return closest_point, min_distance
    
    def get_closest_point_with_position(self, point: Point) -> Tuple[Point, float, int, float]:
        """Find the closest point on this edge and return position information."""
        min_distance = float('inf')
        closest_point = Point(0.0, 0.0)
        best_segment_index = 0
        best_segment_ratio = 0.0
        
        # Check each segment of the edge
        for i in range(len(self.coordinates) - 1):
            start_lat, start_lon = self.coordinates[i]
            end_lat, end_lon = self.coordinates[i + 1]
            
            # Find closest point on this segment
            segment_closest = closest_point_on_segment(
                point.lat, point.lon,
                start_lat, start_lon,
                end_lat, end_lon
            )
            
            distance = point.distance_to(Point(segment_closest[0], segment_closest[1]))
            if distance < min_distance:
                min_distance = distance
                closest_point = Point(segment_closest[0], segment_closest[1])
                best_segment_index = i
                
                # Calculate ratio along this segment
                segment_start = Point(start_lat, start_lon)
                segment_end = Point(end_lat, end_lon)
                segment_total_dist = segment_start.distance_to(segment_end)
                if segment_total_dist > 0:
                    dist_from_start = segment_start.distance_to(closest_point)
                    best_segment_ratio = dist_from_start / segment_total_dist
                else:
                    best_segment_ratio = 0.0
        
        return closest_point, min_distance, best_segment_index, best_segment_ratio
    
    def get_geometry_between_points(self, start_point: Point, end_point: Point) -> Tuple[List[Tuple[float, float]], float]:
        """Extract geometry and distance between two points on this edge."""
        # Get position information for both points
        start_closest, _, start_seg_idx, start_ratio = self.get_closest_point_with_position(start_point)
        end_closest, _, end_seg_idx, end_ratio = self.get_closest_point_with_position(end_point)
        
        # Ensure start comes before end on the edge
        if start_seg_idx > end_seg_idx or (start_seg_idx == end_seg_idx and start_ratio > end_ratio):
            # Swap if needed
            start_closest, end_closest = end_closest, start_closest
            start_seg_idx, end_seg_idx = end_seg_idx, start_seg_idx
            start_ratio, end_ratio = end_ratio, start_ratio
        
        geometry = []
        total_distance = 0.0
        
        # Add the starting point
        geometry.append((start_closest.lat, start_closest.lon))
        
        # If both points are on the same segment
        if start_seg_idx == end_seg_idx:
            geometry.append((end_closest.lat, end_closest.lon))
            total_distance = start_closest.distance_to(end_closest)
        else:
            # Add coordinates from start segment to end of that segment
            if start_seg_idx + 1 < len(self.coordinates):
                next_coord = self.coordinates[start_seg_idx + 1]
                geometry.append(next_coord)
                total_distance += start_closest.distance_to(Point(next_coord[0], next_coord[1]))
            
            # Add all intermediate coordinates
            for i in range(start_seg_idx + 1, end_seg_idx):
                if i + 1 < len(self.coordinates):
                    curr_coord = self.coordinates[i]
                    next_coord = self.coordinates[i + 1]
                    geometry.append(next_coord)
                    total_distance += haversine_distance(curr_coord[0], curr_coord[1], next_coord[0], next_coord[1])
            
            # Add the ending point
            if len(geometry) > 1:
                prev_point = Point(geometry[-1][0], geometry[-1][1])
                total_distance += prev_point.distance_to(end_closest)
            geometry.append((end_closest.lat, end_closest.lon))
        
        return geometry, total_distance
    
    def get_geometry_to_node(self, point: Point, target_node_id: int) -> Tuple[List[Tuple[float, float]], float]:
        """Get geometry from a point on this edge to one of the edge's nodes following the edge."""
        # Get position information for the point
        closest_point, _, seg_idx, ratio = self.get_closest_point_with_position(point)
        
        # Determine which end node to navigate to
        if target_node_id not in [self.start_node, self.end_node]:
            raise ValueError(f"Target node {target_node_id} is not an endpoint of edge {self.id}")
        
        geometry = []
        total_distance = 0.0
        
        # Add the starting point
        geometry.append((closest_point.lat, closest_point.lon))
        
        # Navigate to the target node
        if target_node_id == self.end_node:
            # Navigate towards the end of the edge
            # Add coordinates from current segment to end of edge
            if seg_idx + 1 < len(self.coordinates):
                next_coord = self.coordinates[seg_idx + 1]
                geometry.append(next_coord)
                total_distance += closest_point.distance_to(Point(next_coord[0], next_coord[1]))
            
            # Add all remaining coordinates to the end
            for i in range(seg_idx + 1, len(self.coordinates) - 1):
                curr_coord = self.coordinates[i]
                next_coord = self.coordinates[i + 1]
                geometry.append(next_coord)
                total_distance += haversine_distance(curr_coord[0], curr_coord[1], next_coord[0], next_coord[1])
        else:
            # Navigate towards the start of the edge (target_node_id == self.start_node)
            # Add coordinates from current segment back to start of edge
            for i in range(seg_idx, 0, -1):
                curr_coord = self.coordinates[i]
                prev_coord = self.coordinates[i - 1]
                geometry.append(prev_coord)
                total_distance += haversine_distance(curr_coord[0], curr_coord[1], prev_coord[0], prev_coord[1])
            
            # Adjust first segment distance from closest point to first added coordinate
            if len(geometry) > 1:
                first_added = Point(geometry[1][0], geometry[1][1])
                # Remove the approximate distance and add the exact distance
                if seg_idx > 0:
                    total_distance -= haversine_distance(self.coordinates[seg_idx][0], self.coordinates[seg_idx][1], 
                                                       self.coordinates[seg_idx - 1][0], self.coordinates[seg_idx - 1][1])
                total_distance += closest_point.distance_to(first_added)
        
        return geometry, total_distance

    def get_geometry_from_node(self, source_node_id: int, target_point: Point) -> Tuple[List[Tuple[float, float]], float]:
        """Get geometry from one of the edge's nodes to a point on this edge following the edge."""
        # Determine which end node we're starting from
        if source_node_id not in [self.start_node, self.end_node]:
            raise ValueError(f"Source node {source_node_id} is not an endpoint of edge {self.id}")
        
        # Get position information for the target point
        closest_point, _, seg_idx, ratio = self.get_closest_point_with_position(target_point)
        
        geometry = []
        total_distance = 0.0
        
        if source_node_id == self.start_node:
            # Navigate from start of edge towards the target point
            # Add the starting node coordinate
            geometry.append(self.coordinates[0])
            
            # Add coordinates from start to the target segment
            for i in range(0, seg_idx):
                curr_coord = self.coordinates[i]
                next_coord = self.coordinates[i + 1]
                geometry.append(next_coord)
                total_distance += haversine_distance(curr_coord[0], curr_coord[1], next_coord[0], next_coord[1])
            
            # Add distance from last coordinate to the closest point
            if seg_idx > 0:
                last_coord = Point(self.coordinates[seg_idx][0], self.coordinates[seg_idx][1])
                total_distance += last_coord.distance_to(closest_point)
            
            # Add the target point
            geometry.append((closest_point.lat, closest_point.lon))
        else:
            # Navigate from end of edge towards the target point (source_node_id == self.end_node)
            # Add the starting node coordinate
            geometry.append(self.coordinates[-1])
            
            # Add coordinates from end back to the target segment
            for i in range(len(self.coordinates) - 1, seg_idx, -1):
                curr_coord = self.coordinates[i]
                prev_coord = self.coordinates[i - 1]
                geometry.append(prev_coord)
                total_distance += haversine_distance(curr_coord[0], curr_coord[1], prev_coord[0], prev_coord[1])
            
            # Add distance from last coordinate to the closest point
            if seg_idx + 1 < len(self.coordinates):
                last_coord = Point(self.coordinates[seg_idx + 1][0], self.coordinates[seg_idx + 1][1])
                total_distance += last_coord.distance_to(closest_point)
            
            # Add the target point
            geometry.append((closest_point.lat, closest_point.lon))
        
        return geometry, total_distance
    
    def get_nearest_node_via_edge(self, point: Point) -> Tuple[int, float]:
        """Find which end node of this edge is closer to reach via the edge geometry."""
        closest_point, _, seg_idx, ratio = self.get_closest_point_with_position(point)
        
        # Calculate distance to start node via edge
        distance_to_start = 0.0
        for i in range(seg_idx, 0, -1):
            curr_coord = self.coordinates[i]
            prev_coord = self.coordinates[i - 1]
            distance_to_start += haversine_distance(curr_coord[0], curr_coord[1], prev_coord[0], prev_coord[1])
        
        # Add distance from closest point to segment start
        if seg_idx > 0:
            segment_start = Point(self.coordinates[seg_idx][0], self.coordinates[seg_idx][1])
            distance_to_start += closest_point.distance_to(segment_start)
        
        # Calculate distance to end node via edge
        distance_to_end = 0.0
        for i in range(seg_idx, len(self.coordinates) - 1):
            curr_coord = self.coordinates[i]
            next_coord = self.coordinates[i + 1]
            distance_to_end += haversine_distance(curr_coord[0], curr_coord[1], next_coord[0], next_coord[1])
        
        # Add distance from closest point to segment end
        if seg_idx + 1 < len(self.coordinates):
            segment_end = Point(self.coordinates[seg_idx + 1][0], self.coordinates[seg_idx + 1][1])
            distance_to_end += closest_point.distance_to(segment_end)
        
        # Return the closer node and the distance to it
        if distance_to_start <= distance_to_end:
            return self.start_node, distance_to_start
        else:
            return self.end_node, distance_to_end


def haversine_distance(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Calculate the geodesic distance between two points using Haversine formula."""
    R = 6371000  # Earth's radius in meters
    
    # Convert to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)
    
    # Haversine formula
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    
    a = (math.sin(dlat / 2) ** 2 + 
         math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    return R * c


def closest_point_on_segment(px: float, py: float, 
                           ax: float, ay: float, 
                           bx: float, by: float) -> Tuple[float, float]:
    """Find the closest point on line segment AB to point P."""
    # Vector from A to B
    ab_x = bx - ax
    ab_y = by - ay
    
    # Vector from A to P
    ap_x = px - ax
    ap_y = py - ay
    
    # Project AP onto AB
    ab_length_sq = ab_x * ab_x + ab_y * ab_y
    
    if ab_length_sq == 0:
        # A and B are the same point
        return (ax, ay)
    
    t = (ap_x * ab_x + ap_y * ab_y) / ab_length_sq
    
    # Clamp t to [0, 1] to stay on the segment
    t = max(0, min(1, t))
    
    # Calculate the closest point
    closest_x = ax + t * ab_x
    closest_y = ay + t * ab_y
    
    return (closest_x, closest_y)


class WaterwayGraph:
    """Represents the waterway network graph."""
    
    def __init__(self, nodes: List[Tuple[float, float]], edges: List[Dict]):
        self.nodes = [Point(lat, lon) for lat, lon in nodes]
        self.edges = []
        self.adjacency_list = {}
        
        # Build edge objects and adjacency list
        for i, edge_data in enumerate(edges):
            edge = Edge(
                id=i,
                start_node=edge_data['start'],
                end_node=edge_data['end'],
                length=edge_data['length'],
                coordinates=edge_data['coordinates']
            )
            self.edges.append(edge)
            
            # Build adjacency list for pathfinding
            start = edge_data['start']
            end = edge_data['end']
            
            if start not in self.adjacency_list:
                self.adjacency_list[start] = []
            if end not in self.adjacency_list:
                self.adjacency_list[end] = []
                
            self.adjacency_list[start].append((end, edge.length, i))
            self.adjacency_list[end].append((start, edge.length, i))
    
    def find_closest_edge(self, point: Point) -> Tuple[Edge, Point, float]:
        """Find the closest edge to the given point."""
        if not self.edges:
            raise ValueError("No edges available in the graph")
        
        min_distance = float('inf')
        closest_edge = self.edges[0]  # Initialize with first edge
        closest_point_on_edge = Point(0.0, 0.0)  # Will be overwritten
        
        print(f"  Searching through {len(self.edges)} edges for closest to ({point.lat:.6f}, {point.lon:.6f})")
        
        for edge in self.edges:
            edge_closest_point, distance = edge.get_closest_point_on_edge(point)
            
            if distance < min_distance:
                min_distance = distance
                closest_edge = edge
                closest_point_on_edge = edge_closest_point
        
        print(f"  Found closest edge {closest_edge.id} at distance {min_distance:.2f}m")
        print(f"  Closest point on edge: ({closest_point_on_edge.lat:.6f}, {closest_point_on_edge.lon:.6f})")
        
        return closest_edge, closest_point_on_edge, min_distance
    
    def dijkstra(self, start_node: int, end_node: int) -> Tuple[List[int], float]:
        """Find shortest path between two nodes using Dijkstra's algorithm."""
        if start_node == end_node:
            return [start_node], 0.0
        
        distances = {node: float('inf') for node in range(len(self.nodes))}
        distances[start_node] = 0.0
        previous = {}
        visited = set()
        
        # Priority queue: (distance, node_id)
        pq = [(0.0, start_node)]
        
        while pq:
            current_distance, current_node = heapq.heappop(pq)
            
            if current_node in visited:
                continue
                
            visited.add(current_node)
            
            if current_node == end_node:
                # Reconstruct path
                path = []
                node = end_node
                while node is not None:
                    path.append(node)
                    node = previous.get(node)
                path.reverse()
                return path, distances[end_node]
            
            # Check neighbors
            if current_node in self.adjacency_list:
                for neighbor, edge_length, edge_id in self.adjacency_list[current_node]:
                    if neighbor not in visited:
                        new_distance = current_distance + edge_length
                        
                        if new_distance < distances[neighbor]:
                            distances[neighbor] = new_distance
                            previous[neighbor] = current_node
                            heapq.heappush(pq, (new_distance, neighbor))
        
        # No path found
        return [], float('inf')
    
    def dijkstra_to_all_reachable(self, start_node: int) -> Tuple[Dict[int, float], Dict[int, int]]:
        """Find shortest distances and paths from start_node to all reachable nodes."""
        distances = {node: float('inf') for node in range(len(self.nodes))}
        distances[start_node] = 0.0
        previous = {}
        visited = set()
        
        # Priority queue: (distance, node_id)
        pq = [(0.0, start_node)]
        
        while pq:
            current_distance, current_node = heapq.heappop(pq)
            
            if current_node in visited:
                continue
                
            visited.add(current_node)
            
            # Check neighbors
            if current_node in self.adjacency_list:
                for neighbor, edge_length, edge_id in self.adjacency_list[current_node]:
                    if neighbor not in visited:
                        new_distance = current_distance + edge_length
                        
                        if new_distance < distances[neighbor]:
                            distances[neighbor] = new_distance
                            previous[neighbor] = current_node
                            heapq.heappush(pq, (new_distance, neighbor))
        
        return distances, previous
    
    def find_farthest_reachable_towards_target(self, start_node: int, target_point: Point) -> Tuple[int, float, float]:
        """Find the farthest reachable node from start_node in the direction of target_point."""
        distances, previous = self.dijkstra_to_all_reachable(start_node)
        
        best_node = start_node
        best_distance_along_waterway = 0.0
        best_distance_to_target = self.nodes[start_node].distance_to(target_point)
        
        # Find the reachable node that gets closest to the target (minimizes straight-line distance to target)
        # while using the waterway network as much as possible
        for node_id, waterway_distance in distances.items():
            if waterway_distance != float('inf') and waterway_distance > 0:  # Node is reachable and not the start
                node_point = self.nodes[node_id]
                distance_to_target = node_point.distance_to(target_point)
                
                # Prefer nodes that get closer to the target, prioritizing longer waterway distances for ties
                if (distance_to_target < best_distance_to_target or 
                    (distance_to_target == best_distance_to_target and waterway_distance > best_distance_along_waterway)):
                    best_node = node_id
                    best_distance_along_waterway = waterway_distance
                    best_distance_to_target = distance_to_target
        
        return best_node, best_distance_along_waterway, best_distance_to_target
    
    def reconstruct_path_to_node(self, target_node: int, previous: Dict[int, int], start_node: int) -> List[int]:
        """Reconstruct path from start_node to target_node using previous dictionary."""
        # If target_node is not reachable from start_node, return empty path
        if target_node not in previous and target_node != start_node:
            return []
        
        # Special case: if target is the start node, return single-node path  
        if target_node == start_node:
            return [start_node]
        
        path = []
        node = target_node
        while node is not None:
            path.append(node)
            node = previous.get(node)
        path.reverse()
        return path
    
    def get_path_geometry(self, node_path: List[int]) -> List[Tuple[float, float]]:
        """Get the geometry coordinates for a path through nodes."""
        if len(node_path) < 2:
            return []
        
        geometry = []
        
        for i in range(len(node_path) - 1):
            start_node = node_path[i]
            end_node = node_path[i + 1]
            
            # Find the edge connecting these nodes
            edge_found = False
            for edge in self.edges:
                if ((edge.start_node == start_node and edge.end_node == end_node) or
                    (edge.start_node == end_node and edge.end_node == start_node)):
                    
                    # Add edge coordinates (in correct direction)
                    edge_coords = edge.coordinates.copy()
                    if edge.start_node == end_node:  # Reverse direction
                        edge_coords.reverse()
                    
                    # Add coordinates, avoiding duplicates at junctions
                    if not geometry:
                        geometry.extend(edge_coords)
                    else:
                        geometry.extend(edge_coords[1:])  # Skip first coordinate to avoid duplicate
                    
                    edge_found = True
                    break
            
            if not edge_found:
                print(f"  Warning: No edge found between nodes {start_node} and {end_node}")
                # Add straight line as fallback
                if not geometry:
                    geometry.append((self.nodes[start_node].lat, self.nodes[start_node].lon))
                geometry.append((self.nodes[end_node].lat, self.nodes[end_node].lon))
        
        return geometry


class WaterwayRouteCalculator:
    """Main route calculator class."""
    
    def __init__(self, nodes_file: str, edges_file: str):
        print(f"Loading waterway network from {nodes_file} and {edges_file}")
        
        # Load nodes
        with gzip.open(nodes_file, 'rt', encoding='utf-8') as f:
            nodes_data = json.load(f)
        print(f"Loaded {len(nodes_data)} nodes")
        
        # Load edges
        with gzip.open(edges_file, 'rt', encoding='utf-8') as f:
            edges_data = json.load(f)
        print(f"Loaded {len(edges_data)} edges")
        
        # Build graph
        self.graph = WaterwayGraph(nodes_data, edges_data)
        print(f"Built graph with {len(self.graph.nodes)} nodes and {len(self.graph.edges)} edges")
    
    def calculate_route(self, waypoints: List[Point]) -> Dict:
        """Calculate route through multiple waypoints."""
        print(f"\n{'='*60}")
        print(f"WATERWAY ROUTE CALCULATION")
        print(f"{'='*60}")
        print(f"Waypoints: {len(waypoints)}")
        for i, wp in enumerate(waypoints):
            print(f"  {i+1}: ({wp.lat:.6f}, {wp.lon:.6f})")
        
        route_segments = []
        total_distance = 0.0
        all_geometry = []
        
        for i in range(len(waypoints) - 1):
            start_point = waypoints[i]
            end_point = waypoints[i + 1]
            
            print(f"\n--- Segment {i+1}: Waypoint {i+1} to Waypoint {i+2} ---")
            
            # Find closest edges to start and end points
            print(f"Finding closest edge to start point ({start_point.lat:.6f}, {start_point.lon:.6f})")
            start_edge, start_point_on_edge, start_distance = self.graph.find_closest_edge(start_point)
            
            print(f"Finding closest edge to end point ({end_point.lat:.6f}, {end_point.lon:.6f})")
            end_edge, end_point_on_edge, end_distance = self.graph.find_closest_edge(end_point)
            
            # Check if we need to connect to the waterway network
            segment_geometry = []
            segment_distance = 0.0
            
            # Connect to the waterway network following edge geometry
            start_node_for_pathfinding = None
            
            # Follow edge geometry from waypoint to nearest node of start edge
            if start_distance > 0.1:  # Only add if not already on the edge
                nearest_start_node, distance_to_start_node = start_edge.get_nearest_node_via_edge(start_point)
                print(f"Following edge geometry from waypoint to node {nearest_start_node} ({distance_to_start_node:.2f}m)")
                
                # Get geometry from waypoint to closest point on edge, then along edge to nearest node
                segment_geometry.append((start_point.lat, start_point.lon))
                segment_distance += start_distance
                
                # Follow edge geometry to the nearest node
                edge_to_node_geometry, edge_to_node_distance = start_edge.get_geometry_to_node(start_point, nearest_start_node)
                if len(edge_to_node_geometry) > 1:
                    segment_geometry.extend(edge_to_node_geometry[1:])  # Skip first point (already added above as closest point)
                    segment_distance += edge_to_node_distance
                
                start_node_for_pathfinding = nearest_start_node
            else:
                # Already on the edge, find nearest node
                nearest_start_node, distance_to_start_node = start_edge.get_nearest_node_via_edge(start_point)
                print(f"Waypoint is on edge, using nearest node {nearest_start_node} ({distance_to_start_node:.2f}m)")
                
                # Follow edge geometry to the nearest node
                edge_to_node_geometry, edge_to_node_distance = start_edge.get_geometry_to_node(start_point, nearest_start_node)
                segment_geometry.extend(edge_to_node_geometry)
                segment_distance += edge_to_node_distance
                
                start_node_for_pathfinding = nearest_start_node
            
            # Find path through waterway network
            final_connection_needed = True
            
            # Determine end node for pathfinding and handle final connection
            end_node_for_pathfinding = None
            
            if start_edge.id == end_edge.id:
                print(f"Start and end points are on the same edge {start_edge.id}")
                # Both points are on the same edge - we need to handle this specially
                
                # Find the nearest nodes for both points
                nearest_end_node, distance_to_end_node = end_edge.get_nearest_node_via_edge(end_point)
                
                # If both points use the same nearest node, connect directly along edge
                if start_node_for_pathfinding == nearest_end_node:
                    print(f"  Both points connect to same node {nearest_end_node}, using direct edge connection")
                    # Follow edge geometry from start point to end point
                    edge_geometry, edge_distance = start_edge.get_geometry_between_points(start_point, end_point)
                    if len(edge_geometry) > 1:
                        # Skip first point since we might already be at a point on the edge
                        segment_geometry.extend(edge_geometry[1:])
                        segment_distance += edge_distance
                    final_connection_needed = False
                else:
                    print(f"  Start connects to node {start_node_for_pathfinding}, end connects to node {nearest_end_node}")
                    # Use pathfinding between the two nodes, then connect to end point
                    end_node_for_pathfinding = nearest_end_node
            else:
                print(f"Finding waterway path from edge {start_edge.id} to edge {end_edge.id}")
                # Choose the better end node for pathfinding based on overall route efficiency
                # Try both nodes and see which gives a better overall path
                start_node_coord = self.graph.nodes[start_node_for_pathfinding]
                
                # Get coordinates for both possible end nodes
                end_option1_coord = self.graph.nodes[end_edge.start_node]
                end_option2_coord = self.graph.nodes[end_edge.end_node]
                
                # Calculate straight-line distances from start node to both end options
                dist_to_option1 = start_node_coord.distance_to(end_option1_coord)
                dist_to_option2 = start_node_coord.distance_to(end_option2_coord)
                
                # Calculate edge distances from end point to both end options
                option1_edge_distance = 0.0
                option2_edge_distance = 0.0
                
                closest_point, _, seg_idx, ratio = end_edge.get_closest_point_with_position(end_point)
                
                # Distance to start node (option 1) via edge
                for i in range(seg_idx, 0, -1):
                    curr_coord = end_edge.coordinates[i]
                    prev_coord = end_edge.coordinates[i - 1]
                    option1_edge_distance += haversine_distance(curr_coord[0], curr_coord[1], prev_coord[0], prev_coord[1])
                if seg_idx > 0:
                    segment_start = Point(end_edge.coordinates[seg_idx][0], end_edge.coordinates[seg_idx][1])
                    option1_edge_distance += closest_point.distance_to(segment_start)
                
                # Distance to end node (option 2) via edge  
                for i in range(seg_idx, len(end_edge.coordinates) - 1):
                    curr_coord = end_edge.coordinates[i]
                    next_coord = end_edge.coordinates[i + 1]
                    option2_edge_distance += haversine_distance(curr_coord[0], curr_coord[1], next_coord[0], next_coord[1])
                if seg_idx + 1 < len(end_edge.coordinates):
                    segment_end = Point(end_edge.coordinates[seg_idx + 1][0], end_edge.coordinates[seg_idx + 1][1])
                    option2_edge_distance += closest_point.distance_to(segment_end)
                
                # Choose the option that minimizes the overall route (pathfinding + edge distance)
                # We use a weighted sum: pathfinding distance + edge distance
                total_option1 = dist_to_option1 + option1_edge_distance
                total_option2 = dist_to_option2 + option2_edge_distance
                
                print(f"  Option 1 (start node {end_edge.start_node}): pathfinding={dist_to_option1:.2f}m, edge={option1_edge_distance:.2f}m, total={total_option1:.2f}m")
                print(f"  Option 2 (end node {end_edge.end_node}): pathfinding={dist_to_option2:.2f}m, edge={option2_edge_distance:.2f}m, total={total_option2:.2f}m")
                
                if total_option1 <= total_option2:
                    nearest_end_node = end_edge.start_node
                    distance_to_end_node = option1_edge_distance
                    print(f"  Selected start node {nearest_end_node} (better total cost)")
                else:
                    nearest_end_node = end_edge.end_node
                    distance_to_end_node = option2_edge_distance
                    print(f"  Selected end node {nearest_end_node} (better total cost)")
                
                end_node_for_pathfinding = nearest_end_node
                
            # If we have different edges or different nodes on same edge, do pathfinding
            if end_node_for_pathfinding is not None and start_node_for_pathfinding != end_node_for_pathfinding:
                # Do pathfinding between the nodes
                path, path_distance = self.graph.dijkstra(start_node_for_pathfinding, end_node_for_pathfinding)
                if path and len(path) > 1:
                    print(f"  Found waterway path: {len(path)} nodes, {path_distance:.2f}m")
                    path_geometry = self.graph.get_path_geometry(path)
                    if path_geometry and len(path_geometry) > 1:
                        # Skip first coordinate to avoid duplication with the last coordinate from start edge
                        segment_geometry.extend(path_geometry[1:])
                        segment_distance += path_distance
                    
                    # Now add connection from end of path to final waypoint via edge geometry
                    if end_distance > 0.1:
                        print(f"Following edge geometry from node {end_node_for_pathfinding} to final waypoint ({distance_to_end_node:.2f}m)")
                        edge_from_node_geometry, edge_from_node_distance = end_edge.get_geometry_from_node(end_node_for_pathfinding, end_point)
                        if len(edge_from_node_geometry) > 1:
                            segment_geometry.extend(edge_from_node_geometry[1:])  # Skip first to avoid duplication
                            segment_distance += edge_from_node_distance
                        
                        # Add the final waypoint
                        segment_geometry.append((end_point.lat, end_point.lon))
                        segment_distance += end_distance
                    else:
                        print(f"End waypoint is already on edge, following edge geometry ({distance_to_end_node:.2f}m)")
                        edge_from_node_geometry, edge_from_node_distance = end_edge.get_geometry_from_node(end_node_for_pathfinding, end_point)
                        if len(edge_from_node_geometry) > 1:
                            segment_geometry.extend(edge_from_node_geometry[1:])  # Skip first to avoid duplication
                            segment_distance += edge_from_node_distance
                    
                    final_connection_needed = False
                else:
                    print(f"  No waterway path found between nodes {start_node_for_pathfinding} and {end_node_for_pathfinding}")
                    # Fall back to disconnected route handling
                    route_segments_found, final_handled = self._find_disconnected_route(
                        start_edge, start_point_on_edge, 
                        end_edge, end_point_on_edge, 
                        end_point
                    )
                    
                    # Add all route segments to geometry
                    for route_segment in route_segments_found:
                        segment_geometry.extend(route_segment['geometry'])
                        segment_distance += route_segment['distance']
                        print(f"  Added route segment: {route_segment['type']}, {route_segment['distance']:.2f}m, {len(route_segment['geometry'])} points")
                    
                    if final_handled:
                        final_connection_needed = False
            
            # Handle any remaining final connection needed
            if final_connection_needed and end_distance > 0.1:
                print(f"Adding remaining connection to final waypoint ({end_distance:.2f}m)")
                segment_geometry.append((end_point.lat, end_point.lon))
                segment_distance += end_distance
            
            print(f"Segment {i+1} completed: {segment_distance:.2f}m, {len(segment_geometry)} coordinates")
            
            route_segments.append({
                'start_waypoint': i + 1,
                'end_waypoint': i + 2,
                'distance_m': segment_distance,
                'geometry': segment_geometry,
                'start_edge_id': start_edge.id,
                'end_edge_id': end_edge.id,
                'start_edge_distance_m': start_distance,
                'end_edge_distance_m': end_distance
            })
            
            total_distance += segment_distance
            all_geometry.extend(segment_geometry)
        
        print(f"\n{'='*60}")
        print(f"ROUTE CALCULATION SUMMARY")
        print(f"{'='*60}")
        print(f"Total distance: {total_distance:.2f}m")
        print(f"Total geometry points: {len(all_geometry)}")
        print(f"Route segments: {len(route_segments)}")
        
        return {
            'type': 'route_calculation_result',
            'total_distance_m': total_distance,
            'total_geometry_points': len(all_geometry),
            'segments': route_segments,
            'geometry': all_geometry
        }
    
    def _find_disconnected_route(self, start_edge: Edge, start_point_on_edge: Point, 
                                end_edge: Edge, end_point_on_edge: Point, 
                                end_waypoint: Point) -> Tuple[List[Dict], bool]:
        """Find route through potentially disconnected waterway network."""
        route_segments = []
        final_handled = False  # Track whether we handled the final connection
        
        # First, try direct connection between edges
        best_direct_path = []
        best_direct_distance = float('inf')
        
        # Try all combinations of start/end nodes from the two edges
        start_nodes = [start_edge.start_node, start_edge.end_node]
        end_nodes = [end_edge.start_node, end_edge.end_node]
        
        for start_node in start_nodes:
            for end_node in end_nodes:
                path, distance = self.graph.dijkstra(start_node, end_node)
                if path and distance < best_direct_distance:
                    best_direct_path = path
                    best_direct_distance = distance
                    print(f"  Found direct path via nodes {start_node} -> {end_node}: {len(path)} nodes, {distance:.2f}m")
        
        if best_direct_path:
            print(f"Using direct waterway path: {len(best_direct_path)} nodes, {best_direct_distance:.2f}m")
            path_geometry = self.graph.get_path_geometry(best_direct_path)
            
            if path_geometry:
                route_segments.append({
                    'type': 'waterway_path',
                    'geometry': path_geometry,
                    'distance': best_direct_distance,
                    'nodes': best_direct_path
                })
            
            return route_segments, final_handled
        
        # No direct path found - analyze disconnected networks
        print(f"No direct path found - analyzing disconnected network routing")
        
        # Strategy: Route through waterway network as far as possible towards destination,
        # then bridge to the destination network and continue through waterway to target
        
        best_route_config = None
        best_total_distance = float('inf')
        
        # For each start node, find the optimal route that maximizes waterway usage
        for start_node in start_nodes:
            start_distances, start_previous = self.graph.dijkstra_to_all_reachable(start_node)
            reachable_start_nodes = [node for node, dist in start_distances.items() if dist != float('inf')]
            print(f"  Start node {start_node}: {len(reachable_start_nodes)} reachable nodes")
            
            # Find the point in start network that minimizes bridge distance to ANY point in end network
            for end_node in end_nodes:
                end_distances, end_previous = self.graph.dijkstra_to_all_reachable(end_node)
                reachable_end_nodes = [node for node, dist in end_distances.items() if dist != float('inf')]
                print(f"  End node {end_node}: {len(reachable_end_nodes)} reachable nodes")
                
                # Find optimal bridge connection between the two networks
                min_bridge_distance = float('inf')
                best_bridge_start = None
                best_bridge_end = None
                
                for start_bridge_node in reachable_start_nodes:
                    start_bridge_point = self.graph.nodes[start_bridge_node]
                    
                    for end_bridge_node in reachable_end_nodes:
                        end_bridge_point = self.graph.nodes[end_bridge_node]
                        bridge_distance = start_bridge_point.distance_to(end_bridge_point)
                        
                        if bridge_distance < min_bridge_distance:
                            min_bridge_distance = bridge_distance
                            best_bridge_start = start_bridge_node
                            best_bridge_end = end_bridge_node
                
                if best_bridge_start is not None and best_bridge_end is not None:
                    # Calculate waterway distances
                    start_waterway_dist = start_distances[best_bridge_start]
                    end_waterway_dist = end_distances[best_bridge_end]
                    total_distance = start_waterway_dist + min_bridge_distance + end_waterway_dist
                    
                    print(f"    Route option: start_waterway={start_waterway_dist:.1f}m, bridge={min_bridge_distance:.1f}m, end_waterway={end_waterway_dist:.1f}m, total={total_distance:.1f}m")
                    
                    if total_distance < best_total_distance:
                        best_total_distance = total_distance
                        
                        # Store the complete route configuration
                        start_route = self.graph.reconstruct_path_to_node(best_bridge_start, start_previous, start_node)
                        # For end route, we want to go FROM best_bridge_end TO end_node
                        # But dijkstra was run from end_node, so we get the path and reverse it
                        end_route_reversed = self.graph.reconstruct_path_to_node(best_bridge_end, end_previous, end_node)
                        end_route = list(reversed(end_route_reversed)) if end_route_reversed else []
                        
                        best_route_config = {
                            'start_route': start_route,
                            'start_distance': start_waterway_dist,
                            'bridge_start': best_bridge_start,
                            'bridge_end': best_bridge_end,
                            'bridge_distance': min_bridge_distance,
                            'end_route': end_route,
                            'end_distance': end_waterway_dist,
                            'total_distance': total_distance
                        }
        
        if best_route_config is not None:
            print(f"Found optimal disconnected route:")
            print(f"  Start waterway: {len(best_route_config['start_route'])} nodes, {best_route_config['start_distance']:.2f}m")
            print(f"  Bridge: {best_route_config['bridge_distance']:.2f}m")
            print(f"  End waterway: {len(best_route_config['end_route'])} nodes, {best_route_config['end_distance']:.2f}m")
            print(f"  Total distance: {best_route_config['total_distance']:.2f}m")
            
            # Add the waterway route segments
            if best_route_config['start_distance'] > 0:
                start_path_geometry = self.graph.get_path_geometry(best_route_config['start_route'])
                if start_path_geometry:
                    route_segments.append({
                        'type': 'waterway_path_start_component',
                        'geometry': start_path_geometry,
                        'distance': best_route_config['start_distance'],
                        'nodes': best_route_config['start_route']
                    })
                    print(f"  Added start waterway segment: {len(best_route_config['start_route'])} nodes, {best_route_config['start_distance']:.2f}m")
            
            # Add the bridge connection
            bridge_start = self.graph.nodes[best_route_config['bridge_start']]
            bridge_end = self.graph.nodes[best_route_config['bridge_end']]
            
            route_segments.append({
                'type': 'straight_line_bridge',
                'geometry': [(bridge_start.lat, bridge_start.lon), (bridge_end.lat, bridge_end.lon)],
                'distance': best_route_config['bridge_distance'],
                'nodes': [best_route_config['bridge_start'], best_route_config['bridge_end']]
            })
            print(f"  Added bridge segment: {best_route_config['bridge_distance']:.2f}m")
            
            # Add the end waterway route segment
            if best_route_config['end_distance'] > 0 and len(best_route_config['end_route']) > 0:
                end_path_geometry = self.graph.get_path_geometry(best_route_config['end_route'])
                if end_path_geometry:
                    route_segments.append({
                        'type': 'waterway_path_end_component',
                        'geometry': end_path_geometry,
                        'distance': best_route_config['end_distance'],
                        'nodes': best_route_config['end_route']
                    })
                    print(f"  Added end waterway segment: {len(best_route_config['end_route'])} nodes, {best_route_config['end_distance']:.2f}m")
                    
                    # Check if we need to add edge geometry from the end of waterway route to the destination
                    if end_path_geometry:
                        end_waterway_point = Point(end_path_geometry[-1][0], end_path_geometry[-1][1])
                        end_waterway_edge, end_waterway_point_on_edge, end_waterway_distance = self.graph.find_closest_edge(end_waterway_point)
                        
                        print(f"  End waterway point: ({end_waterway_point.lat:.6f}, {end_waterway_point.lon:.6f})")
                        print(f"  Destination point: ({end_point_on_edge.lat:.6f}, {end_point_on_edge.lon:.6f})")
                        
                        if (end_waterway_edge.id == end_edge.id and end_waterway_distance < 10.0):
                            # Both the end of waterway and destination are on the same edge
                            print(f"  Adding edge geometry from end of waterway to destination")
                            final_edge_geometry, final_edge_distance = end_edge.get_geometry_between_points(end_waterway_point_on_edge, end_point_on_edge)
                            print(f"  Final edge geometry: {len(final_edge_geometry)} points, {final_edge_distance:.2f}m")
                            
                            # Check if geometry is in reverse direction (first point should be near end_waterway_point)
                            if len(final_edge_geometry) > 1:
                                first_point = Point(final_edge_geometry[0][0], final_edge_geometry[0][1])
                                last_point = Point(final_edge_geometry[-1][0], final_edge_geometry[-1][1])
                                
                                dist_to_first = end_waterway_point_on_edge.distance_to(first_point)
                                dist_to_last = end_waterway_point_on_edge.distance_to(last_point)
                                
                                print(f"  Distance from end_waterway to first point: {dist_to_first:.2f}m")
                                print(f"  Distance from end_waterway to last point: {dist_to_last:.2f}m")
                                
                                # If geometry is in reverse direction, reverse it
                                if dist_to_last < dist_to_first:
                                    print(f"  Reversing geometry to correct direction")
                                    final_edge_geometry = list(reversed(final_edge_geometry))
                            
                            if len(final_edge_geometry) > 1 and final_edge_distance > 1.0:
                                # Add the edge geometry (skip first point to avoid duplication)
                                route_segments.append({
                                    'type': 'final_edge_geometry',
                                    'geometry': final_edge_geometry[1:],  # Skip first point
                                    'distance': final_edge_distance,
                                    'nodes': []
                                })
                                print(f"  Added final edge geometry: {len(final_edge_geometry)-1} points, {final_edge_distance:.2f}m")
                                final_handled = True  # We handled the final connection with edge geometry
                            else:
                                print(f"  Final edge geometry too short, adding connection point")
                                # Add final connection to end edge point
                                route_segments.append({
                                    'type': 'connection_to_end',
                                    'geometry': [(end_point_on_edge.lat, end_point_on_edge.lon)],
                                    'distance': 0.0,
                                    'nodes': []
                                })
                        else:
                            print(f"  Different edges or too far, adding connection point")
                            # Add final connection to end edge point
                            route_segments.append({
                                'type': 'connection_to_end',
                                'geometry': [(end_point_on_edge.lat, end_point_on_edge.lon)],
                                'distance': 0.0,
                                'nodes': []
                            })
                    else:
                        print(f"  No end path geometry, adding connection point")
                        # Add final connection to end edge point
                        route_segments.append({
                            'type': 'connection_to_end',
                            'geometry': [(end_point_on_edge.lat, end_point_on_edge.lon)],
                            'distance': 0.0,
                            'nodes': []
                        })
                else:
                    print(f"  End route geometry was empty, nodes: {best_route_config['end_route']}")
                    # Add final connection to end edge point
                    route_segments.append({
                        'type': 'connection_to_end',
                        'geometry': [(end_point_on_edge.lat, end_point_on_edge.lon)],
                        'distance': 0.0,
                        'nodes': []
                    })
            else:
                print(f"  Skipped end waterway segment: distance={best_route_config['end_distance']:.2f}m, nodes={len(best_route_config['end_route'])}")
                # Add final connection to end edge point
                route_segments.append({
                    'type': 'connection_to_end',
                    'geometry': [(end_point_on_edge.lat, end_point_on_edge.lon)],
                    'distance': 0.0,
                    'nodes': []
                })
        else:
            # Fallback to straight line if no meaningful waterway routing possible
            print(f"No meaningful waterway routing possible - using straight line")
            bridge_distance = start_point_on_edge.distance_to(end_point_on_edge)
            route_segments.append({
                'type': 'straight_line_fallback',
                'geometry': [(start_point_on_edge.lat, start_point_on_edge.lon), (end_point_on_edge.lat, end_point_on_edge.lon)],
                'distance': bridge_distance,
                'nodes': []
            })
        
        return route_segments, final_handled
    
    def create_geojson_output(self, route_result: Dict, waypoints: List[Point]) -> Dict:
        """Create GeoJSON output for the calculated route."""
        features = []
        
        # Add the main route line
        if route_result['geometry']:
            # Convert from (lat, lon) to (lon, lat) for GeoJSON
            coordinates = [[lon, lat] for lat, lon in route_result['geometry']]
            
            route_feature = {
                'type': 'Feature',
                'geometry': {
                    'type': 'LineString',
                    'coordinates': coordinates
                },
                'properties': {
                    'type': 'route',
                    'total_distance_m': route_result['total_distance_m'],
                    'segments': len(route_result['segments'])
                }
            }
            features.append(route_feature)
        
        # Add waypoint markers
        for i, waypoint in enumerate(waypoints):
            waypoint_feature = {
                'type': 'Feature',
                'geometry': {
                    'type': 'Point',
                    'coordinates': [waypoint.lon, waypoint.lat]
                },
                'properties': {
                    'type': 'waypoint',
                    'waypoint_number': i + 1
                }
            }
            features.append(waypoint_feature)
        
        # Add segment information as separate features
        for i, segment in enumerate(route_result['segments']):
            if segment['geometry']:
                segment_coordinates = [[lon, lat] for lat, lon in segment['geometry']]
                
                segment_feature = {
                    'type': 'Feature',
                    'geometry': {
                        'type': 'LineString',
                        'coordinates': segment_coordinates
                    },
                    'properties': {
                        'type': 'route_segment',
                        'segment_number': i + 1,
                        'distance_m': segment['distance_m'],
                        'start_waypoint': segment['start_waypoint'],
                        'end_waypoint': segment['end_waypoint'],
                        'start_edge_id': segment['start_edge_id'],
                        'end_edge_id': segment['end_edge_id'],
                        'start_edge_distance_m': segment['start_edge_distance_m'],
                        'end_edge_distance_m': segment['end_edge_distance_m']
                    }
                }
                features.append(segment_feature)
        
        return {
            'type': 'FeatureCollection',
            'features': features,
            'properties': {
                'generator': 'waterway_route_calculator.py',
                'calculation_summary': {
                    'total_distance_m': route_result['total_distance_m'],
                    'waypoints': len(waypoints),
                    'segments': len(route_result['segments']),
                    'geometry_points': route_result['total_geometry_points']
                }
            }
        }


def parse_coordinate_pairs(coord_strings: List[str]) -> List[Point]:
    """Parse coordinate pair strings into Point objects."""
    waypoints = []
    for coord_str in coord_strings:
        try:
            lat_str, lon_str = coord_str.split(',')
            lat = float(lat_str.strip())
            lon = float(lon_str.strip())
            waypoints.append(Point(lat, lon))
        except ValueError:
            raise ValueError(f"Invalid coordinate format: '{coord_str}'. Expected format: 'lat,lon'")
    
    return waypoints


def main():
    parser = argparse.ArgumentParser(
        description='Calculate waterway routes between waypoints using OSM waterway graph data',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python waterway_route_calculator.py test.nodes.json.gz test.edges.json.gz 52.5,13.4 52.52,13.42
  python waterway_route_calculator.py data.nodes.json.gz data.edges.json.gz -- -34.5,-56.1 -34.52,-56.12 -34.54,-56.14
  python waterway_route_calculator.py nodes.json.gz edges.json.gz 52.5,13.4 52.52,13.42 --output route.geojson

Input coordinate format: lat,lon (decimal degrees)
Output: GeoJSON with route geometry and debug information
Use -- before coordinates if they start with minus signs to avoid parsing as options.
        """
    )
    
    parser.add_argument('nodes_file', help='Path to nodes.json.gz file')
    parser.add_argument('edges_file', help='Path to edges.json.gz file')
    parser.add_argument('--output', '-o', help='Output GeoJSON file (default: print to stdout)')
    parser.add_argument('waypoints', nargs='+', help='Waypoints as lat,lon pairs')
    
    args = parser.parse_args()
    
    if len(args.waypoints) < 2:
        print("Error: At least 2 waypoints are required", file=sys.stderr)
        sys.exit(1)
    
    try:
        # Print version information
        print(f"Waterway Route Calculator v{SCRIPT_VERSION}")
        print()
        
        # Parse waypoints
        waypoints = parse_coordinate_pairs(args.waypoints)
        
        # Create route calculator
        calculator = WaterwayRouteCalculator(args.nodes_file, args.edges_file)
        
        # Calculate route
        route_result = calculator.calculate_route(waypoints)
        
        # Create GeoJSON output
        geojson_output = calculator.create_geojson_output(route_result, waypoints)
        
        # Output result
        if args.output:
            with open(args.output, 'w') as f:
                json.dump(geojson_output, f, indent=2)
            print(f"\nRoute saved to {args.output}")
        else:
            print(json.dumps(geojson_output, indent=2))
    
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()